version: '3.8'

services:
  app:
    hostname: 'user-microservice'
    container_name: 'user-microservice'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - local-network
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  local-network:
    name: network-user-microservice
